# Generated by Django 4.0 on 2022-02-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpacker', '0004_alter_package_image_alter_package_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(default='B.png', upload_to=''),
        ),
    ]
