# Generated by Django 4.0 on 2022-02-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpacker', '0006_package_mode_alter_package_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='phone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='aadhar',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='customuser',
            name='aadhar_image',
            field=models.ImageField(default='B.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
