# Generated by Django 4.0 on 2022-02-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backpacker', '0007_remove_agent_phone_customuser_aadhar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='aadhar',
            new_name='aadhar_no',
        ),
    ]
