# Generated by Django 4.0 on 2022-02-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpacker', '0008_rename_aadhar_customuser_aadhar_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='boarding',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
