# Generated by Django 4.0 on 2022-02-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpacker', '0009_book_boarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='boarding',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
