# Generated by Django 4.2 on 2023-09-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('prize', models.IntegerField()),
                ('cname', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=30)),
                ('productimg', models.FileField(upload_to='e_commerce_app/static/images')),
            ],
        ),
        migrations.CreateModel(
            name='new_register_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('profilepic', models.FileField(upload_to='e_commerce_app/static/images')),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
