# Generated by Django 4.2 on 2023-09-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_register_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('uusername', models.CharField(max_length=30)),
                ('uemail', models.EmailField(max_length=254)),
                ('uphone', models.IntegerField()),
                ('uprofilepic', models.FileField(upload_to='e_commerce_app/static/images')),
                ('upassword', models.CharField(max_length=30)),
            ],
        ),
    ]
