# Generated by Django 4.2 on 2023-09-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0002_user_register_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_register_model',
            old_name='uname',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='user_register_model',
            name='lname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
