# Generated by Django 4.2 on 2023-09-19 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0003_rename_uname_user_register_model_fname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_prod',
            old_name='quantity',
            new_name='age_range',
        ),
        migrations.RenameField(
            model_name='add_prod',
            old_name='cname',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='add_prod',
            old_name='description',
            new_name='catagories',
        ),
        migrations.RenameField(
            model_name='add_prod',
            old_name='pname',
            new_name='color',
        ),
    ]
