# Generated by Django 4.2 on 2023-09-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0004_rename_quantity_add_prod_age_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_prod',
            name='age_range',
            field=models.CharField(max_length=30),
        ),
    ]
