# Generated by Django 4.2 on 2023-09-20 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0005_alter_add_prod_age_range'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_prod',
            old_name='catagories',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='user_register_model',
            old_name='fname',
            new_name='uname',
        ),
        migrations.RemoveField(
            model_name='user_register_model',
            name='lname',
        ),
    ]
