# Generated by Django 4.2 on 2023-09-20 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0006_rename_catagories_add_prod_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_register_model',
            name='profilepic',
        ),
        migrations.RemoveField(
            model_name='user_register_model',
            name='uprofilepic',
        ),
    ]
