# Generated by Django 4.2 on 2023-09-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0007_remove_new_register_model_profilepic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('prod_id', models.IntegerField()),
                ('categories', models.CharField(max_length=30)),
                ('prize', models.IntegerField()),
                ('brand', models.CharField(max_length=30)),
                ('productimg', models.FileField(upload_to='')),
            ],
        ),
    ]
