# Generated by Django 4.2 on 2023-09-22 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0009_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='cartmodel',
        ),
    ]
