# Generated by Django 4.2 on 2023-09-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0011_new_register_model_pimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_register_model',
            name='pimage',
            field=models.FileField(upload_to='e_commerce_app/static'),
        ),
        migrations.AlterField(
            model_name='user_register_model',
            name='proimage',
            field=models.FileField(upload_to='e_commerce_app/static'),
        ),
    ]
