# Generated by Django 4.2 on 2023-10-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0012_alter_new_register_model_pimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('roadname', models.CharField(max_length=30)),
                ('housename', models.CharField(max_length=30)),
            ],
        ),
    ]
