# Generated by Django 4.2 on 2023-10-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0013_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
