# Generated by Django 4.2 on 2023-10-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0014_address_phone_address_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='housename',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='roadname',
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
