# Generated by Django 4.2 on 2023-10-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0015_rename_housename_address_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='lname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
