# Generated by Django 4.2 on 2023-10-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0016_address_lname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='address',
            new_name='addressmodel',
        ),
    ]
